export interface UserEntry {
  userId: string
  name: string
  password: string
  position: string
  department: string
  type: "admin" | "dept" | "employee"
}

// يوزرات الإدارة العليا
export const ADMIN_USERS: UserEntry[] = [
  { userId: "gm",   name: "م/ أحمد شوقي",  password: "9528",   position: "رئيس مجلس الإدارة", department: "الإدارة العليا",  type: "admin" },
  { userId: "QTY",  name: "محمود إسماعيل", password: "mm212",  position: "مدير الجودة",       department: "الجودة",          type: "admin" },
  { userId: "QTY2", name: "شادي مظهر",     password: "mm2123", position: "مهندس جودة",        department: "الجودة",          type: "admin" },
]

// يوزرات الأقسام
export const DEPT_USERS: UserEntry[] = [
  { userId: "office.shawky",      name: "مكتب م/ أحمد شوقي",         password: "111111", position: "قسم مكتب م/ أحمد شوقي",         department: "مكتب م/ أحمد شوقي",         type: "dept" },
  { userId: "general.management", name: "الإدارة العامة",             password: "222222", position: "قسم الإدارة العامة",             department: "الإدارة العامة",             type: "dept" },
  { userId: "items.managers",     name: "مديرين البنود",              password: "333333", position: "قسم مديرين البنود",              department: "مديرين البنود",              type: "dept" },
  { userId: "hr.department",      name: "الموارد البشرية",            password: "444444", position: "قسم الموارد البشرية",            department: "الموارد البشرية",            type: "dept" },
  { userId: "social.media",       name: "السوشيال ميديا",             password: "555555", position: "قسم السوشيال ميديا",             department: "السوشيال ميديا",             type: "dept" },
  { userId: "eng.october",        name: "مهندسين - أكتوبر",           password: "666666", position: "قسم مهندسين أكتوبر",             department: "مهندسين - أكتوبر",           type: "dept" },
  { userId: "eng.newcairo",       name: "مهندسين - القاهرة الجديدة",  password: "777777", position: "قسم مهندسين القاهرة الجديدة",    department: "مهندسين - القاهرة الجديدة",  type: "dept" },
  { userId: "eng.capital",        name: "مهندسين - العاصمة",          password: "888888", position: "قسم مهندسين العاصمة",            department: "مهندسين - العاصمة",          type: "dept" },
  { userId: "eng.tagamoa",        name: "مهندسين - التجمع",           password: "999999", position: "قسم مهندسين التجمع",             department: "مهندسين - التجمع",           type: "dept" },
  { userId: "eng.downtown",       name: "مهندسين - وسط",              password: "101010", position: "قسم مهندسين وسط",               department: "مهندسين - وسط",              type: "dept" },
  { userId: "eng.regions",        name: "مهندسين - الأقاليم",         password: "111222", position: "قسم مهندسين الأقاليم",           department: "مهندسين - الأقاليم",         type: "dept" },
  { userId: "quality.dept",       name: "الجودة",                     password: "121212", position: "قسم الجودة",                     department: "الجودة",                     type: "dept" },
  { userId: "inspection.dept",    name: "المعاينات",                  password: "131313", position: "قسم المعاينات",                  department: "المعاينات",                  type: "dept" },
  { userId: "legal.dept",         name: "الشؤون القانونية",           password: "141414", position: "قسم الشؤون القانونية",           department: "الشؤون القانونية",           type: "dept" },
  { userId: "accounting.dept",    name: "الحسابات",                   password: "151515", position: "قسم الحسابات",                   department: "الحسابات",                   type: "dept" },
  { userId: "carpentry.dept",     name: "النجارة",                    password: "161616", position: "قسم النجارة",                    department: "النجارة",                    type: "dept" },
  { userId: "technical.office",   name: "المكتب الفني",               password: "171717", position: "المكتب الفني",                   department: "المكتب الفني",               type: "dept" },
  { userId: "customer.service",   name: "خدمة العملاء",               password: "181818", position: "قسم خدمة العملاء",               department: "خدمة العملاء",               type: "dept" },
  { userId: "furniture.dept",     name: "الفرش والديكور",             password: "191919", position: "قسم الفرش والديكور",             department: "الفرش والديكور",             type: "dept" },
  { userId: "contracts.dept",     name: "التعاقدات",                  password: "202020", position: "قسم التعاقدات",                  department: "التعاقدات",                  type: "dept" },
  { userId: "telesales.dept",     name: "تلي سيلز",                   password: "212121", position: "قسم تلي سيلز",                   department: "تلي سيلز",                   type: "dept" },
  { userId: "ceramic.dept",       name: "السيراميك",                  password: "222333", position: "قسم السيراميك",                  department: "السيراميك",                  type: "dept" },
  { userId: "operations.dept",    name: "التشغيل",                    password: "232323", position: "قسم التشغيل",                    department: "التشغيل",                    type: "dept" },
  { userId: "buffet.dept",        name: "البوفيه",                    password: "242424", position: "قسم البوفيه",                    department: "البوفيه",                    type: "dept" },
  { userId: "electric.showroom",  name: "معرض الكهرباء",              password: "252525", position: "معرض الكهرباء",                  department: "معرض الكهرباء",              type: "dept" },
  { userId: "paint.showroom",     name: "معرض الدهانات",              password: "262626", position: "معرض الدهانات",                  department: "معرض الدهانات",              type: "dept" },
  { userId: "it.department",      name: "IT",                         password: "272727", position: "قسم تكنولوجيا المعلومات",        department: "IT",                         type: "dept" },
  { userId: "vehicles.dept",      name: "السيارات",                   password: "282828", position: "قسم السيارات",                   department: "السيارات",                   type: "dept" },
]

// يوزرات الموظفين الفردية
export const EMPLOYEE_USERS: UserEntry[] = [
  { userId: "malak",               name: "ملك رؤوف",                        password: "482498", position: "مديرة مكتب م/ أحمد شوقي",          department: "مكتب م/ أحمد شوقي",         type: "employee" },
  { userId: "mohamed.hassan",      name: "محمد حسن",                        password: "511776", position: "المدير العام",                       department: "الإدارة العامة",             type: "employee" },
  { userId: "mahmoud.afandina",    name: "م/ محمود عبد الغني (أفندينا)",    password: "861380", position: "مدير قسم الجبس بورد والرخام",        department: "مديرين البنود",              type: "employee" },
  { userId: "mohamed.shawky",      name: "م/ محمد شوقي",                    password: "593311", position: "مدير قسم النجارة",                   department: "مديرين البنود",              type: "employee" },
  { userId: "mohamed.naguib",      name: "م/ محمد نجيب",                    password: "726955", position: "مدير بند الكهرباء",                  department: "مديرين البنود",              type: "employee" },
  { userId: "ahmed.abdelbaset",    name: "م/ أحمد عبد الباسط",              password: "706597", position: "مدير بند السيراميك",                 department: "مديرين البنود",              type: "employee" },
  { userId: "mohamed.youssef",     name: "م/ محمد يوسف",                    password: "766726", position: "مدير التكيفات والتوريدات",            department: "مديرين البنود",              type: "employee" },
  { userId: "ahmed.abdelghani",    name: "م/ أحمد عبد الغني",               password: "706598", position: "مدير بند توريدات الكهرباء",          department: "مديرين البنود",              type: "employee" },
  { userId: "mohamed.abdelmoneam", name: "محمد عبد المنعم",                 password: "800543", position: "مدير الموارد البشرية",               department: "الموارد البشرية",            type: "employee" },
  { userId: "hagar",               name: "هاجر عبد العزيز",                 password: "800544", position: "HR",                                 department: "الموارد البشرية",            type: "employee" },
  { userId: "heba.khaled",         name: "هبه خالد",                        password: "356988", position: "HR",                                 department: "الموارد البشرية",            type: "employee" },
  { userId: "abdelrahman.fayez",   name: "عبد الرحمن فايز علي",             password: "448579", position: "HR",                                 department: "الموارد البشرية",            type: "employee" },
  { userId: "mostafa.shawky",      name: "م/ مصطفى شوقي",                   password: "776674", position: "Social Media Manager",               department: "السوشيال ميديا",             type: "employee" },
  { userId: "ahmed.keta",          name: "أحمد عبد الغني (كيتا)",           password: "800526", position: "Deputy Manager",                     department: "السوشيال ميديا",             type: "employee" },
  { userId: "ashraf.zaki",         name: "اشرف ذكي",                        password: "827701", position: "Producer - Photographer",             department: "السوشيال ميديا",             type: "employee" },
  { userId: "anas.atef",           name: "انس عاطف محمد",                   password: "340773", position: "Producer",                           department: "السوشيال ميديا",             type: "employee" },
  { userId: "mahmoud.alaa",        name: "محمود علاء انصاري",               password: "010618", position: "Moderator",                          department: "السوشيال ميديا",             type: "employee" },
  { userId: "moamen.mostafa",      name: "مؤمن مصطفى",                      password: "587005", position: "Content Creator",                    department: "السوشيال ميديا",             type: "employee" },
  { userId: "ahmed.hamed",         name: "احمد حامد",                       password: "426815", position: "مدير منطقة أكتوبر",                  department: "مهندسين - أكتوبر",           type: "employee" },
  { userId: "ahmed.ragab",         name: "احمد رجب",                        password: "912261", position: "مهندس - أكتوبر",                     department: "مهندسين - أكتوبر",           type: "employee" },
  { userId: "mohamed.obaida",      name: "محمد عبيده",                      password: "690947", position: "مهندس - أكتوبر",                     department: "مهندسين - أكتوبر",           type: "employee" },
  { userId: "ahmed.ashraf",        name: "احمد اشرف",                       password: "500188", position: "مهندس - أكتوبر",                     department: "مهندسين - أكتوبر",           type: "employee" },
  { userId: "mohamed.amin",        name: "محمد امين",                       password: "860050", position: "مهندس - أكتوبر",                     department: "مهندسين - أكتوبر",           type: "employee" },
  { userId: "islam.adel",          name: "اسلام عادل",                      password: "044029", position: "مهندس - أكتوبر",                     department: "مهندسين - أكتوبر",           type: "employee" },
  { userId: "ali.mohamed",         name: "علي",                             password: "997103", position: "مهندس - أكتوبر",                     department: "مهندسين - أكتوبر",           type: "employee" },
  { userId: "mostafa.kamal",       name: "مصطفي كمال",                      password: "589130", position: "مدير منطقة القاهرة الجديدة",         department: "مهندسين - القاهرة الجديدة",  type: "employee" },
  { userId: "mostafa.eid",         name: "مصطفي عيد",                       password: "498820", position: "مهندس - القاهرة الجديدة",            department: "مهندسين - القاهرة الجديدة",  type: "employee" },
  { userId: "mohamed.gamal",       name: "محمد جمال",                       password: "864455", position: "مهندس - القاهرة الجديدة",            department: "مهندسين - القاهرة الجديدة",  type: "employee" },
  { userId: "abdelrahman.mohamed", name: "عبدالرحمن محمد",                  password: "159043", position: "مهندس - القاهرة الجديدة",            department: "مهندسين - القاهرة الجديدة",  type: "employee" },
  { userId: "ahmed.elazaby",       name: "احمد العزبي",                     password: "273742", position: "مدير منطقة العاصمة الإدارية",        department: "مهندسين - العاصمة",          type: "employee" },
  { userId: "hussein.faid",        name: "حسين فيض الله",                   password: "322922", position: "مهندس - العاصمة الإدارية",           department: "مهندسين - العاصمة",          type: "employee" },
  { userId: "mohamed.ashraf",      name: "محمد اشرف",                       password: "492117", position: "مهندس - العاصمة الإدارية",           department: "مهندسين - العاصمة",          type: "employee" },
  { userId: "mahmoud.mohsen",      name: "محمود محسن",                      password: "640037", position: "مهندس - العاصمة الإدارية",           department: "مهندسين - العاصمة",          type: "employee" },
  { userId: "mohamed.maher",       name: "محمد ماهر",                       password: "629354", position: "مهندس - العاصمة الإدارية",           department: "مهندسين - العاصمة",          type: "employee" },
  { userId: "mohamed.medhat",      name: "محمد مدحت",                       password: "593094", position: "مدير منطقة التجمع الخامس",           department: "مهندسين - التجمع",           type: "employee" },
  { userId: "hossam.ghandour",     name: "حسام الغدور",                     password: "244495", position: "مهندس - التجمع الخامس",              department: "مهندسين - التجمع",           type: "employee" },
  { userId: "karim.samy",          name: "كريم سامي",                       password: "183789", position: "مهندس - التجمع الخامس",              department: "مهندسين - التجمع",           type: "employee" },
  { userId: "mohsen.abdelrazek",   name: "محسن عبدالرازق",                  password: "091234", position: "مهندس - التجمع الخامس",              department: "مهندسين - التجمع",           type: "employee" },
  { userId: "abdelnaby.morgan",    name: "عبدالنبي مرجان",                  password: "334460", position: "مهندس - التجمع الخامس",              department: "مهندسين - التجمع",           type: "employee" },
  { userId: "emad.shalaby",        name: "عماد شلبي",                       password: "455556", position: "مهندس - التجمع الخامس",              department: "مهندسين - التجمع",           type: "employee" },
  { userId: "mohamed.ghannam",     name: "محمد غنام",                       password: "003089", position: "مهندس - التجمع الخامس",              department: "مهندسين - التجمع",           type: "employee" },
  { userId: "ahmed.bassyouni",     name: "احمد بسيوني",                     password: "221382", position: "مدير منطقة وسط",                     department: "مهندسين - وسط",              type: "employee" },
  { userId: "mohamed.gameel",      name: "محمد محمود الجميل",               password: "264221", position: "مهندس - وسط",                        department: "مهندسين - وسط",              type: "employee" },
  { userId: "amr.khaled",          name: "عمرو خالد",                       password: "107025", position: "مهندس - وسط",                        department: "مهندسين - وسط",              type: "employee" },
  { userId: "abdelrahman.iraqi",   name: "عبدالرحمن العراقي",               password: "074988", position: "مهندس - وسط",                        department: "مهندسين - وسط",              type: "employee" },
  { userId: "bishoy",              name: "بيشوي",                           password: "948825", position: "مهندس - وسط",                        department: "مهندسين - وسط",              type: "employee" },
  { userId: "mohamed.salah",       name: "محمد صلاح",                       password: "416769", position: "مدير منطقة الأقاليم",                department: "مهندسين - الأقاليم",         type: "employee" },
  { userId: "ali.mokhtar",         name: "علي مختار",                       password: "602018", position: "مهندس - الأقاليم",                   department: "مهندسين - الأقاليم",         type: "employee" },
  { userId: "ahmed.elsheikh",      name: "احمد الشيخ (السادات)",            password: "277915", position: "مهندس - الأقاليم",                   department: "مهندسين - الأقاليم",         type: "employee" },
  { userId: "bayoumy",             name: "بيومي",                           password: "973235", position: "مهندس - الأقاليم",                   department: "مهندسين - الأقاليم",         type: "employee" },
  { userId: "shenouda",            name: "شنوده",                           password: "285129", position: "مهندس - الأقاليم",                   department: "مهندسين - الأقاليم",         type: "employee" },
  { userId: "ahmed.awad",          name: "احمد عوض",                        password: "936377", position: "مهندس - الأقاليم",                   department: "مهندسين - الأقاليم",         type: "employee" },
  { userId: "mohamed.abdelazeem", name: "محمد عبدالعظيم",                  password: "020263", position: "مهندس - الأقاليم",                   department: "مهندسين - الأقاليم",         type: "employee" },
  { userId: "mahmoud.abouzeid",   name: "محمود ابو زيد",                   password: "479394", position: "مهندس - الأقاليم",                   department: "مهندسين - الأقاليم",         type: "employee" },
  { userId: "mahmoud.ismail",     name: "محمود اسماعيل",                   password: "121549", position: "مدير الجودة",                        department: "الجودة",                     type: "employee" },
  { userId: "shady.mazhar",       name: "شادي مظهر",                       password: "704637", position: "مهندس جودة",                         department: "الجودة",                     type: "employee" },
  { userId: "moamen.yousry",      name: "مؤمن يسري",                       password: "293383", position: "مسئول الخدمات / المشتريات",          department: "المعاينات",                  type: "employee" },
  { userId: "amr.abdullah",       name: "المستشار عمرو عبد الله",          password: "088704", position: "مدير الإدارة القانونية",             department: "الشؤون القانونية",           type: "employee" },
  { userId: "mahmoud.gharib",     name: "محمود غريب",                      password: "734095", position: "شؤون قانونية",                       department: "الشؤون القانونية",           type: "employee" },
  { userId: "wael.rafat",         name: "وائل رأفت أمين",                  password: "660739", position: "مدير الحسابات",                      department: "الحسابات",                   type: "employee" },
  { userId: "rady.shehata",       name: "راضي شحاته",                      password: "864533", position: "أمين خزينة",                         department: "الحسابات",                   type: "employee" },
  { userId: "mai.essam",          name: "مي عصام عبد العزيز",              password: "925721", position: "محاسبة",                             department: "الحسابات",                   type: "employee" },
  { userId: "khaled.mohyeldin",   name: "خالد محي الدين عبد القادر",       password: "296258", position: "محاسب",                              department: "الحسابات",                   type: "employee" },
  { userId: "khaled.atef",        name: "خالد عاطف عبد الغني محمد",        password: "329792", position: "محاسب مخزن",                         department: "الحسابات",                   type: "employee" },
  { userId: "heba.tawfik",        name: "هبه توفيق",                       password: "183223", position: "مسئولة تحويلات",                     department: "الحسابات",                   type: "employee" },
  { userId: "karim.atef",         name: "كريم عاطف",                       password: "922582", position: "مدير قسم الحسابات",                  department: "الحسابات",                   type: "employee" },
  { userId: "hasnaa.emad",        name: "حسناء عماد",                      password: "544901", position: "مسئول إضافات",                       department: "الحسابات",                   type: "employee" },
  { userId: "abdullah.essam",     name: "عبد الله عصام",                   password: "672999", position: "مسئول إضافات",                       department: "الحسابات",                   type: "employee" },
  { userId: "mohamed.salem",      name: "محمد سالم صلاح الدين",            password: "494073", position: "مسئول إضافات",                       department: "الحسابات",                   type: "employee" },
  { userId: "ashraf.saber",       name: "أشرف صابر",                       password: "165846", position: "جودة نجارة",                         department: "النجارة",                    type: "employee" },
  { userId: "esraa.galal",        name: "إسراء جلال",                      password: "594811", position: "مسئول معرض الأثاث",                  department: "النجارة",                    type: "employee" },
  { userId: "heba.aboelmagd",     name: "هبه أبو المجد",                   password: "827704", position: "سكرتيرة",                            department: "النجارة",                    type: "employee" },
  { userId: "basmala.zaki",       name: "بسمله زكي عزت السعيد",            password: "101122", position: "خدمة عملاء النجارة",                 department: "النجارة",                    type: "employee" },
  { userId: "mahmoud.hesham",     name: "محمود هشام محمود نجاتي",          password: "861381", position: "محاسب قسم النجارة",                  department: "النجارة",                    type: "employee" },
  { userId: "abdelrahman.bahary", name: "عبد الرحمن البحري",               password: "705524", position: "سواق",                               department: "النجارة",                    type: "employee" },
  { userId: "hesham.magdy",       name: "هشام مجدي كمال",                  password: "253329", position: "محاسب قسم النجارة",                  department: "النجارة",                    type: "employee" },
  { userId: "ahmed.hassan",       name: "أحمد حسن مصطفى حسن عبده",        password: "466551", position: "مهندس نجارة",                        department: "النجارة",                    type: "employee" },
  { userId: "hadeer.mahmoud",     name: "هدير محمود محمد",                 password: "259055", position: "تصميمات النجارة",                    department: "النجارة",                    type: "employee" },
  { userId: "abdelmoneam.yahya",  name: "عبد المنعم يحيى عبد المنعم",      password: "788530", position: "مسئول قسم النجارة",                  department: "النجارة",                    type: "employee" },
  { userId: "hassan.mahmoud",     name: "حسن محمود عبد الحميد",            password: "621041", position: "نجار",                               department: "النجارة",                    type: "employee" },
  { userId: "abdelrahman.hesham", name: "عبد الرحمن هشام",                 password: "250312", position: "عامل النجارة",                       department: "النجارة",                    type: "employee" },
  { userId: "amr.hesham",         name: "عمرو هشام محمد",                  password: "148438", position: "عامل مصنع النجارة",                  department: "النجارة",                    type: "employee" },
  { userId: "islam.khaled",       name: "إسلام خالد",                      password: "679887", position: "مدير المكتب الفني",                  department: "المكتب الفني",               type: "employee" },
  { userId: "yara.yousry",        name: "يارا يسري شعبان",                 password: "997506", position: "مهندسة مكتب فني",                    department: "المكتب الفني",               type: "employee" },
  { userId: "sara.ahmed",         name: "سارة أحمد محمد أحمد",             password: "101181", position: "مهندس مكتب فني",                     department: "المكتب الفني",               type: "employee" },
  { userId: "kyrillos.zakaria",   name: "كيرلس زكريا غطاس عوض",           password: "411913", position: "مهندس مكتب فني",                     department: "المكتب الفني",               type: "employee" },
  { userId: "aya.naeem",          name: "آيه نعيم أنور محمود",             password: "800548", position: "مهندس مكتب فني",                     department: "المكتب الفني",               type: "employee" },
  { userId: "farah.tamer",        name: "فرح تامر محمد",                   password: "473346", position: "مهندس مكتب فني",                     department: "المكتب الفني",               type: "employee" },
  { userId: "abdullah.reda",      name: "عبد الله رضا محمد عبد العزيز",   password: "119496", position: "مهندس مكتب فني",                     department: "المكتب الفني",               type: "employee" },
  { userId: "maryam.youssef",     name: "مريم يوسف",                       password: "593289", position: "مهندسة مكتب فني",                    department: "المكتب الفني",               type: "employee" },
  { userId: "bassant.antar",      name: "بسنت عنتر",                       password: "864603", position: "مديرة خدمة العملاء",                 department: "خدمة العملاء",               type: "employee" },
  { userId: "asmaa.mohamed",      name: "اسماء محمد عبد العليم",           password: "800518", position: "خدمه عملاء العاصمة",                 department: "خدمة العملاء",               type: "employee" },
  { userId: "doaa.gamal",         name: "دعاء جمال عبد المنعم",            password: "841543", position: "خدمة عملاء القاهرة الجديدة",         department: "خدمة العملاء",               type: "employee" },
  { userId: "youssef.magdy",      name: "يوسف مجدي محمد",                  password: "119629", position: "خدمة عملاء وسط - أكتوبر",            department: "خدمة العملاء",               type: "employee" },
  { userId: "ayat.hamed",         name: "ايات حامد حسن علي",               password: "504072", position: "خدمه عملاء",                         department: "خدمة العملاء",               type: "employee" },
  { userId: "ahmed.abdelghani2",  name: "م/ أحمد عبد الغني",               password: "706599", position: "مدير قسم الفرش",                     department: "الفرش والديكور",             type: "employee" },
  { userId: "nada.amr",           name: "ندى عمرو محمد",                   password: "864759", position: "مهندسة بقسم الفرش والديكور",         department: "الفرش والديكور",             type: "employee" },
  { userId: "asmaa.hussein",      name: "أسماء حسين",                      password: "865758", position: "مسؤولة بند التكيفات",                department: "الفرش والديكور",             type: "employee" },
  { userId: "saeed.samir",        name: "سعيد سمير عبد العزيز علي",        password: "086941", position: "مسؤل بند المشتريات الكهربي",         department: "الفرش والديكور",             type: "employee" },
  { userId: "habiba.mansour",     name: "حبيبه منصور",                     password: "367635", position: "موظفه تعاقدات",                      department: "التعاقدات",                  type: "employee" },
  { userId: "rana.waheed",        name: "رنا وحيد",                        password: "630606", position: "موظفه تعاقدات",                      department: "التعاقدات",                  type: "employee" },
  { userId: "neveen.eid",         name: "نيفين عيد محمد",                  password: "545667", position: "موظفه تعاقدات",                      department: "التعاقدات",                  type: "employee" },
  { userId: "youssef.alaa",       name: "يوسف علاء محمد عبد الهادي",       password: "620606", position: "موظف تعاقدات - سيلز",               department: "التعاقدات",                  type: "employee" },
  { userId: "malak.khaled",       name: "ملك خالد خليل",                   password: "863141", position: "موظفه تعاقدات",                      department: "التعاقدات",                  type: "employee" },
  { userId: "hadeer.khaled",      name: "هدير خالد",                       password: "800534", position: "مسئولة تعاقدات",                     department: "التعاقدات",                  type: "employee" },
  { userId: "nada.hamed",         name: "ندى حامد سعيد حامد",              password: "864748", position: "موظفة تلي سيلز",                     department: "تلي سيلز",                   type: "employee" },
  { userId: "mohamed.azab",       name: "محمد عزب عرب محمد السيد",         password: "654499", position: "تلي سيلز",                           department: "تلي سيلز",                   type: "employee" },
  { userId: "fatma.rady",         name: "فاطمه راضي أحمد صادق",            password: "402956", position: "تلي سيلز",                           department: "تلي سيلز",                   type: "employee" },
  { userId: "mohamed.yahya",      name: "محمد يحيي عبدالحميد عبد الرازق",  password: "946616", position: "مسؤول قسم السيراميك",                department: "السيراميك",                  type: "employee" },
  { userId: "omnia.mostafa",      name: "امنيه مصطفى",                     password: "800552", position: "منسق سيراميك",                       department: "السيراميك",                  type: "employee" },
  { userId: "mohamed.yousry",     name: "محمد يسري",                       password: "605351", position: "منسق سيراميك",                       department: "السيراميك",                  type: "employee" },
  { userId: "mohamed.saeed",      name: "محمد سعيد محمد",                  password: "865930", position: "مدير قسم التشغيل",                   department: "التشغيل",                    type: "employee" },
  { userId: "sameh.abdelsabour",  name: "م/ سامح عبد الصبور",              password: "864735", position: "مدير مشاريع",                        department: "التشغيل",                    type: "employee" },
  { userId: "osama.hamdy",        name: "اسامة حمدي أحمد ابراهيم",         password: "800523", position: "مسئول مقاولين",                      department: "التشغيل",                    type: "employee" },
  { userId: "ahmed.khaled",       name: "احمد خالد",                       password: "612784", position: "مسئول مقاولين",                      department: "التشغيل",                    type: "employee" },
  { userId: "hossam.ashraf",      name: "حسام اشرف فرج احمد",              password: "836360", position: "مسئول البوفيه",                      department: "البوفيه",                    type: "employee" },
  { userId: "hanan.abbas",        name: "حنان عباس",                       password: "088455", position: "بوفيه",                              department: "البوفيه",                    type: "employee" },
  { userId: "mohamed.abdelhalim", name: "محمد محمد عبد العليم",            password: "767222", position: "مسئول معرض الكهرباء",                department: "معرض الكهرباء",              type: "employee" },
  { userId: "mahmoud.ali",        name: "محمود علي",                       password: "093894", position: "مسئول معرض الدهانات",                department: "معرض الدهانات",              type: "employee" },
  { userId: "ahmed.abulsoud",     name: "م/ أحمد أبو السعود",              password: "444748", position: "مدير تكنولوجيا المعلومات",           department: "IT",                         type: "employee" },
  { userId: "azzam",              name: "عزام",                            password: "108751", position: "مسؤول السيارات",                     department: "السيارات",                   type: "employee" },
  { userId: "abdelrahman.antar",  name: "عبد الرحمن عنتر",                 password: "827729", position: "موظف مبيعات",                        department: "التعاقدات",                  type: "employee" },
  { userId: "aya.elbieh",         name: "المهندسة آية البيه",              password: "900000", position: "مهندسة مكتب فني",                    department: "المكتب الفني",               type: "employee" },
]

export const ALL_USERS: UserEntry[] = [...ADMIN_USERS, ...DEPT_USERS, ...EMPLOYEE_USERS]
